image: kroniak/ssh-client:3.1
pipelines:
  branches:
    devel: # this staging branch pipeline will deploy to the staging environment
      - step:
          name: Build and release
          script:
          - mkdir -p ~/.ssh
          - (umask  077 ; echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa)
          - echo $ENV_DEV | base64 -d > env-file
          - chmod 400 ~/.ssh/id_rsa
          - echo -e "Host  *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          - ssh ubuntu@ec2-3-133-191-59.us-east-2.compute.amazonaws.com "cd /opt/futurex && git stash && git pull origin devel && git checkout devel && npm install && ng build"
         
