/**
 * Logout
 * # Logout API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';




import { Configuration }                                     from '../configuration';


export interface LogoutServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Logout response
    * Logout
    */
    logoutGet(extraHttpRequestParams?: any): Observable<{}>;

}
